services:
    postgres:
        image: postgres:latest
        restart: always
        user: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db_input:/db_input
        environment:
            - POSTGRES_PASSWORD=advent
        expose:
            - 5432
        ports:
            - 5432:5432
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:
